openapi: 3.0.0
info:
  title: Monkey-App Api Docs
  description: Monkey-App is a bloggin site where user can read blogs, create account share their blogs etc.
  version: 2.2.0
  contact:
    email: monkeyappsupport@cublearner.org
    url: "https://rakeshdhariwal-portfolio.netlify.app"
servers:
  - url: "https://monkeyblogbackend-production.up.railway.app"
  - url: "http://localhost:5000"
    description: Server url to hit request

components:
  securitySchemes:
    bearerAuth:            
      type: http
      description: Add your token like Bearer <AUTH_ACCESS_TOKEN>
      scheme: bearer
      bearerFormat: JWT

# paths for user
paths:
  /user/login:
    post:
      tags:
        - User Related API
      summary: This is login api which will return an token (AUTH_ACCESS_TOKEN) if the user is Authorized
      consumes:
        - application/json
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: 
                - email
                - password
              properties:
                email: 
                  type: string
                password: 
                  type: string
      responses:
        200:
          description: All good and success
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  userInfo:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      themeSide:
                        type: string
        400:
          description: Incorrect Password
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Incorrect Password
        404:
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User not found
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Internal Server error

  /user/verify_auth:
    post:
      tags:
        - User Related API
      summary: The AUTH_ACCESS_TOKEN which is saved while the user gets login is used to verify him\her when they came back to site (used for auto login )
      security:
        - bearerAuth: []
      responses:
        200:
          description: Return User Info
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  userInfo:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      themeSide:
                        type: string
        404:
          description: Auth failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Auth failed
  
  /user/forgotpassword:
    post:
      tags:
        - User Related API
      summary: The route take registered email id new password and send 4 digit otp to registered email for verification to reset password
      responses:
        200:
          description: Return User Info
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                  userInfo:
                    type: object
                    properties:
                      _id:
                        type: string
                      name:
                        type: string
                      themeSide:
                        type: string
        400:
          description: Password must be of 8 character
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Password must be of 8 character
        401:
          description: Unable to send OTP 
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Unable to send OTP
        404:
          description: User Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User Not found
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: User Not found
  /user/forgotpassword/verify:
    post:
      tags:
        - User Related API
      summary: The route take registered email id of which user trying to reset password and send 4 digit otp to which has been send to user registered email
      responses:
        200:
          description: Password Update success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: vPassword Update success  
        400:
          description: Invalid OTP
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Invalid OTP   
        404:
          description:  OTP Expired 
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message:  OTP Expired
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Server Error    
  /user/signup/sendotp:
    post:
      tags:
        - User Related API
      summary: The route take name, email id,  password and send 4 digit otp to  email for verification 
      consumes:
        - application/json
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: 
                - name
                - email
                - password
              properties:
                name: 
                  type: string
                email: 
                  type: string
                password: 
                  type: string
      responses:
        200:
          description: OTP sent to the required email address
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: OTP sent success 
        400:
          description: Password must be of 8 character
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Password must be of 8 character  
        401:
          description: Unable to save details on Database
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Database transiction error
        404:
          description:  User Already Exist || Unable to send otp
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message:  User Already Exist || Unable to send otp
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Server Error    
  /user/signup/verifyuser:
    post:
      tags:
        - User Related API
      summary: Use this route to verify email using otp which has been sent to email
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              required: 
                - email
                - otp
              properties:
                email: 
                  type: string
                otp: 
                  type: string
      responses:
        200:
          description: Registration success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Registration success
        400:
          description: Invalid OTP
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Invalid OTP 
        404:
          description:  OTP expired or not sended yet
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message:  OTP expired or not sended yet
        500:
          description: Internal Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  message: Server Error 

